#pragma once

enum : int {
    IDC_BTN_CAPTURE = 3001,
    IDC_BTN_LEARN,
    IDC_BTN_CLASSIFY,
    IDC_BTN_PREV,
    IDC_BTN_NEXT,
    IDC_BTN_PROMPT,
    IDC_BTN_DELETE,
    IDC_BTN_EXIT,
    IDC_STATUS,
    IDC_PREVIEW,
    IDC_HISTORY
};
